# Generated by Django 5.0.4 on 2024-04-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('user', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=5000)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=5000)),
                ('date', models.DateTimeField()),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
