# Generated by Django 5.0.4 on 2024-04-15 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_db', '0002_posts_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
